[package]
name = "diesel_migrations"
version = "1.4.1"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Migration management for diesel"
documentation = "https://docs.rs/crate/diesel_migrations"
homepage = "http://diesel.rs"


[dependencies]
migrations_internals = "~1.3.0"
migrations_macros = "~1.3.0"

[dev-dependencies]
diesel = { version = "1.3.0", default-features = false, features = ["sqlite", "postgres", "mysql"] }
dotenv = ">=0.8, <0.11"
cfg-if = "0.1.0"
libsqlite3-sys = { version = ">=0.8.0, <0.10.0", optional = true, features = ["min_sqlite_version_3_7_16"] }


[features]
default = []
sqlite = []
postgres = []
mysql = []
